export const ALL_STRETCHES = [

  // ─── NECK ───────────────────────────────────────────
  {
    id: 'n1',
    name: 'Neck Rolls',
    muscle: 'neck',
    duration: 30,
    positions: ['couch', 'standing'],
    feelings: ['tight', 'stressed'],
    tip: 'Move slowly and let gravity do the work. Never roll your neck backwards — keep it to the sides and front only.',
    steps: [
      'Sit or stand tall with your spine straight',
      'Slowly drop your right ear toward your right shoulder',
      'Roll your chin down toward your chest',
      'Continue rolling to the left side',
      'Reverse the direction and repeat slowly',
    ],
  },
  {
    id: 'n2',
    name: 'Ear to Shoulder',
    muscle: 'neck',
    duration: 30,
    positions: ['couch', 'standing', 'lying'],
    feelings: ['tight', 'stressed'],
    tip: 'Drop your ear toward your shoulder and let the weight of your head do the stretching. Place your opposite hand behind your back to deepen it.',
    steps: [
      'Sit or stand with your spine tall',
      'Drop your right ear directly toward your right shoulder',
      'Place your right hand gently on your left temple for extra weight',
      'Hold for 20 seconds feeling the stretch up the left side of your neck',
      'Slowly return to center and switch sides',
    ],
  },
  {
    id: 'n3',
    name: 'Chin Tuck',
    muscle: 'neck',
    duration: 30,
    positions: ['couch', 'standing'],
    feelings: ['tight', 'stressed'],
    tip: 'Gently draw your chin straight back like you\'re making a double chin. This directly combats tech neck by realigning your cervical spine.',
    steps: [
      'Sit or stand looking straight ahead',
      'Without tilting your head, draw your chin straight back',
      'You should feel a gentle stretch at the base of your skull',
      'Hold for 3 seconds then release',
      'Repeat 8 to 10 times slowly',
    ],
  },
  {
    id: 'n4',
    name: 'Scalene Stretch',
    muscle: 'neck',
    duration: 35,
    positions: ['couch', 'standing'],
    feelings: ['tight', 'stressed'],
    tip: 'Tilt your head to one side and rotate your chin slightly upward. This targets the scalene muscles — the most overlooked neck muscles that cause headaches.',
    steps: [
      'Sit tall and place your right hand behind your back',
      'Tilt your head to the left and rotate your chin slightly upward',
      'You should feel the stretch along the right side and front of your neck',
      'Hold for 20 seconds breathing slowly',
      'Return to center and switch sides',
    ],
  },
  {
    id: 'n5',
    name: 'Neck Forward Fold',
    muscle: 'neck',
    duration: 25,
    positions: ['couch', 'standing'],
    feelings: ['tight', 'stressed'],
    tip: 'Let your chin drop toward your chest and interlace your fingers gently behind your head — don\'t pull, just let the weight add a gentle stretch.',
    steps: [
      'Sit or stand with your spine tall',
      'Let your chin drop slowly toward your chest',
      'Interlace your fingers gently behind your head',
      'Do not pull — just let the weight of your hands add gentle pressure',
      'Hold for 20 seconds then slowly lift your head back up',
    ],
  },

  // ─── SHOULDERS ──────────────────────────────────────
  {
    id: 's1',
    name: 'Shoulder Shrugs',
    muscle: 'shoulders',
    duration: 30,
    positions: ['couch', 'standing'],
    feelings: ['tight', 'stressed', 'low-energy'],
    tip: 'Lift your shoulders up toward your ears, hold for 2 seconds, then drop them down completely. Feel the tension release on the drop.',
    steps: [
      'Sit or stand with arms relaxed at your sides',
      'Lift both shoulders up toward your ears as high as possible',
      'Hold at the top for 2 full seconds',
      'Drop them down as far as possible and feel the release',
      'Repeat 8 to 10 times slowly',
    ],
  },
  {
    id: 's2',
    name: 'Cross Body Shoulder Stretch',
    muscle: 'shoulders',
    duration: 30,
    positions: ['couch', 'standing'],
    feelings: ['tight', 'sore'],
    tip: 'Pull your arm across your chest and use your opposite forearm — not your hand — to apply gentle pressure. Keep your elbow below shoulder height.',
    steps: [
      'Stand or sit tall with your back straight',
      'Bring your right arm straight across your chest',
      'Use your left forearm to press it gently toward your body',
      'Keep your right elbow below shoulder height',
      'Hold for 20 seconds then switch arms',
    ],
  },
  {
    id: 's3',
    name: 'Thread the Needle',
    muscle: 'shoulders',
    duration: 40,
    positions: ['lying'],
    feelings: ['tight', 'sore', 'stressed'],
    tip: 'From all fours, slide one arm under your body along the floor with palm facing up. This reaches the deepest part of your shoulder that nothing else touches.',
    steps: [
      'Start on all fours with hands under shoulders and knees under hips',
      'Slide your right arm under your left arm with palm facing up',
      'Lower your right shoulder and cheek toward the floor',
      'Hold and feel the deep stretch through the back of your shoulder',
      'Return to center and repeat on the other side',
    ],
  },
  {
    id: 's4',
    name: 'Sleeper Stretch',
    muscle: 'shoulders',
    duration: 40,
    positions: ['lying'],
    feelings: ['tight', 'sore'],
    tip: 'Lie on your side with your arm out at 90 degrees. Use your other hand to gently push your wrist toward the floor. This is the number one stretch for rotator cuff health.',
    steps: [
      'Lie on your right side with your right arm extended at shoulder height',
      'Bend your right elbow to 90 degrees so your forearm points upward',
      'Use your left hand to gently push your right wrist toward the floor',
      'Hold when you feel tension in the back of your shoulder',
      'Hold for 30 seconds then switch sides',
    ],
  },
  {
    id: 's5',
    name: 'Behind the Back Clasp',
    muscle: 'shoulders',
    duration: 30,
    positions: ['couch', 'standing'],
    feelings: ['tight', 'stressed'],
    tip: 'Clasp your hands behind your back and straighten your arms. Lift your hands slightly and open your chest — this hits your shoulders and chest simultaneously.',
    steps: [
      'Stand or sit tall and clasp your hands behind your back',
      'Straighten your arms and squeeze your shoulder blades together',
      'Lift your clasped hands gently away from your body',
      'Open your chest and lift your chin slightly',
      'Hold for 20 to 30 seconds breathing deeply',
    ],
  },

  // ─── CHEST ──────────────────────────────────────────
  {
    id: 'c1',
    name: 'Chest Opener',
    muscle: 'chest',
    duration: 30,
    positions: ['couch', 'standing'],
    feelings: ['stressed', 'low-energy', 'tight'],
    tip: 'Clasp your hands behind your back and gently squeeze your shoulder blades together. Keep your chin level — don\'t let your head drop forward.',
    steps: [
      'Stand or sit at the edge of your seat',
      'Clasp your hands behind your lower back',
      'Squeeze your shoulder blades together firmly',
      'Lift your chest and keep your chin level',
      'Hold for 20 to 30 seconds and breathe deeply into the front of your chest',
    ],
  },
  {
    id: 'c2',
    name: 'Doorway Chest Stretch',
    muscle: 'chest',
    duration: 35,
    positions: ['standing'],
    feelings: ['tight', 'stressed'],
    tip: 'Place your forearms on a door frame and lean forward gently. Keep your elbows at shoulder height and stagger your stance for balance.',
    steps: [
      'Stand in a doorway and place both forearms on the door frame',
      'Position your elbows at shoulder height',
      'Stagger your feet for stability with one foot forward',
      'Gently lean your body forward through the doorway',
      'Hold when you feel the stretch across your chest and hold for 25 seconds',
    ],
  },
  {
    id: 'c3',
    name: 'Lying Chest Expansion',
    muscle: 'chest',
    duration: 40,
    positions: ['lying'],
    feelings: ['stressed', 'low-energy'],
    tip: 'Lie flat and stretch both arms out to the sides like a T. Let gravity open your chest naturally — place a rolled towel under your spine to deepen it.',
    steps: [
      'Lie flat on your back on the floor',
      'Extend both arms out to the sides at shoulder height forming a T shape',
      'Turn your palms to face the ceiling',
      'Let gravity pull your arms toward the floor and open your chest',
      'Hold for 30 to 40 seconds breathing slowly and deeply',
    ],
  },
  {
    id: 'c4',
    name: 'Prayer Stretch Reverse',
    muscle: 'chest',
    duration: 30,
    positions: ['couch', 'standing'],
    feelings: ['tight', 'stressed'],
    tip: 'Press the backs of your hands together in front of you and push them forward. This is the opposite of prayer pose and deeply stretches the chest and wrists together.',
    steps: [
      'Sit or stand tall with your spine straight',
      'Bring both hands in front of you and press the backs of your hands together',
      'Point your fingers downward',
      'Push your hands forward away from your body',
      'Hold for 20 seconds feeling the stretch across your chest and wrists',
    ],
  },
  {
    id: 'c5',
    name: 'Pec Minor Release',
    muscle: 'chest',
    duration: 35,
    positions: ['lying'],
    feelings: ['tight', 'sore'],
    tip: 'Lie on your back and place a tennis ball under your collarbone area. Gently roll to find tender spots and hold for 5 seconds each. The pec minor is the root cause of most rounded shoulder posture.',
    steps: [
      'Lie face down and place a tennis ball just below your collarbone',
      'Slowly shift your weight onto the ball to apply pressure',
      'Find a tender spot and hold still for 5 seconds',
      'Take a slow deep breath and feel the tissue release',
      'Move the ball slightly and repeat on new spots for the full duration',
    ],
  },

  // ─── BACK ───────────────────────────────────────────
  {
    id: 'b1',
    name: 'Seated Spinal Twist',
    muscle: 'back',
    duration: 45,
    positions: ['couch'],
    feelings: ['tight', 'sore'],
    tip: 'Sit tall before you twist — imagine a string pulling the top of your head toward the ceiling. Breathe out as you rotate deeper.',
    steps: [
      'Sit tall at the edge of your seat with feet flat on the floor',
      'Place your right hand on your left knee and your left hand behind you',
      'Inhale to lengthen your spine',
      'Exhale and rotate your torso to the left as far as comfortable',
      'Hold for 20 seconds then repeat on the other side',
    ],
  },
  {
    id: 'b2',
    name: 'Supine Knee Hug',
    muscle: 'back',
    duration: 45,
    positions: ['lying'],
    feelings: ['sore', 'stressed'],
    tip: 'Pull both knees gently into your chest and let your lower back press flat into the floor. Rock side to side slightly for a bonus massage.',
    steps: [
      'Lie flat on your back with legs extended',
      'Bring both knees up toward your chest',
      'Wrap your arms around your shins and gently pull your knees in',
      'Let your lower back press completely flat into the floor',
      'Rock gently side to side for 30 to 45 seconds',
    ],
  },
  {
    id: 'b3',
    name: 'Child\'s Pose',
    muscle: 'back',
    duration: 45,
    positions: ['lying'],
    feelings: ['sore', 'stressed', 'tight'],
    tip: 'Reach your arms forward and let your hips sink toward your heels. Walk your hands to the left and right to stretch each side of your back separately.',
    steps: [
      'Start on all fours with knees hip-width apart',
      'Sink your hips back toward your heels',
      'Reach both arms forward along the floor as far as possible',
      'Let your forehead rest on the floor and relax completely',
      'Walk your hands to the left and right to target each side of your back',
    ],
  },
  {
    id: 'b4',
    name: 'Cat Cow Stretch',
    muscle: 'back',
    duration: 40,
    positions: ['lying'],
    feelings: ['tight', 'sore', 'low-energy'],
    tip: 'Move slowly between arching and rounding your back. Breathe in as you arch, breathe out as you round — let your breath lead the movement.',
    steps: [
      'Start on all fours with hands under shoulders and knees under hips',
      'Inhale and arch your back downward letting your belly drop toward the floor',
      'Lift your head and tailbone upward — this is cow pose',
      'Exhale and round your back upward toward the ceiling',
      'Tuck your chin and tailbone — this is cat pose — and repeat slowly',
    ],
  },
  {
    id: 'b5',
    name: '90-90 Spinal Rotation',
    muscle: 'back',
    duration: 45,
    positions: ['lying'],
    feelings: ['tight', 'sore'],
    tip: 'Lie on your back with knees stacked at 90 degrees. Drop both knees to one side while keeping your shoulders flat. This is one of the most effective thoracic spine releases you can do lying down.',
    steps: [
      'Lie on your back with knees bent and feet flat on the floor',
      'Extend both arms out to the sides at shoulder height',
      'Keep your shoulders pressed firmly into the floor',
      'Slowly let both knees fall to the right side',
      'Hold for 20 to 30 seconds then bring knees back up and switch sides',
    ],
  },
  {
    id: 'b6',
    name: 'Standing Back Extension',
    muscle: 'back',
    duration: 20,
    positions: ['standing'],
    feelings: ['tight', 'low-energy'],
    tip: 'Place your hands on your lower back and gently arch backward. Only go as far as is comfortable — this counteracts hours of forward hunching.',
    steps: [
      'Stand tall with feet hip-width apart',
      'Place both hands on your lower back with fingers pointing downward',
      'Gently push your hips forward and arch backward',
      'Look upward and breathe into the front of your chest',
      'Hold for 10 seconds then return slowly to standing',
    ],
  },
  {
    id: 'b7',
    name: 'Seated Forward Fold',
    muscle: 'back',
    duration: 40,
    positions: ['couch', 'lying'],
    feelings: ['tight', 'stressed'],
    tip: 'Hinge from your hips — not your waist. Keep your back flat as long as possible before letting it round. Reach toward your feet without straining.',
    steps: [
      'Sit tall with legs extended straight in front of you',
      'Inhale and lengthen your spine',
      'Hinge forward from your hips keeping your back as flat as possible',
      'Reach your hands toward your feet without forcing it',
      'Hold at the point of mild tension for 30 seconds breathing slowly',
    ],
  },

  // ─── HIPS ───────────────────────────────────────────
  {
    id: 'h1',
    name: 'Lying Hip Stretch',
    muscle: 'hips',
    duration: 45,
    positions: ['lying'],
    feelings: ['tight', 'sore'],
    tip: 'Cross one ankle over the opposite knee and flex that foot to protect your knee joint. The closer you pull your legs to your chest, the deeper the stretch.',
    steps: [
      'Lie on your back with knees bent and feet flat',
      'Cross your right ankle over your left knee',
      'Flex your right foot to protect the knee joint',
      'Lift your left foot off the floor and pull both legs toward your chest',
      'Hold for 30 seconds then switch sides',
    ],
  },
  {
    id: 'h2',
    name: 'Hip Flexor Lunge',
    muscle: 'hips',
    duration: 40,
    positions: ['standing'],
    feelings: ['tight', 'low-energy'],
    tip: 'Tuck your pelvis slightly under — this is the key move most people miss. You should feel the stretch at the front of your back leg\'s hip, not your knee.',
    steps: [
      'Step your right foot forward into a lunge position',
      'Lower your left knee gently to the floor',
      'Tuck your pelvis slightly under — this is crucial',
      'Shift your weight forward until you feel the stretch at the front of your left hip',
      'Hold for 30 seconds then switch legs',
    ],
  },
  {
    id: 'h3',
    name: 'Seated Figure Four',
    muscle: 'hips',
    duration: 45,
    positions: ['couch'],
    feelings: ['tight', 'sore'],
    tip: 'Cross one ankle over the opposite knee and sit up straight. Gently press down on the crossed knee and lean slightly forward to deepen the stretch.',
    steps: [
      'Sit tall at the edge of your seat with feet flat on the floor',
      'Cross your right ankle over your left knee',
      'Sit up straight and keep your back flat',
      'Gently press down on your right knee with your hand',
      'Lean slightly forward from your hips to deepen and hold for 30 seconds',
    ],
  },
  {
    id: 'h4',
    name: 'Butterfly Stretch',
    muscle: 'hips',
    duration: 40,
    positions: ['lying'],
    feelings: ['tight', 'stressed'],
    tip: 'Bring the soles of your feet together and let your knees fall out to the sides. Don\'t push your knees down — just let gravity do the work over time.',
    steps: [
      'Sit on the floor and bring the soles of your feet together',
      'Let your knees fall out to the sides naturally',
      'Hold your feet with both hands and sit up tall',
      'Do not push your knees down — let gravity do the work',
      'Hold for 30 to 40 seconds breathing slowly',
    ],
  },
  {
    id: 'h5',
    name: '90-90 Hip Stretch',
    muscle: 'hips',
    duration: 50,
    positions: ['lying'],
    feelings: ['tight', 'sore'],
    tip: 'Sit with both knees bent at 90 degrees — one in front, one to the side. This is considered the gold standard hip stretch as it addresses both internal and external rotation simultaneously.',
    steps: [
      'Sit on the floor and position your right knee bent at 90 degrees in front of you',
      'Position your left knee bent at 90 degrees out to your left side',
      'Sit up as tall as possible and keep your hips level',
      'Lean forward slightly over your front shin to feel the stretch',
      'Hold for 40 seconds then switch the direction of your legs',
    ],
  },
  {
    id: 'h6',
    name: 'Couch Stretch',
    muscle: 'hips',
    duration: 50,
    positions: ['couch'],
    feelings: ['tight', 'sore'],
    tip: 'Kneel with one shin against the couch and the other foot on the floor. Stay upright and tuck your pelvis. This is the most effective hip flexor stretch for people who sit all day.',
    steps: [
      'Kneel facing away from the couch',
      'Place your right shin and foot up against the couch cushion',
      'Step your left foot forward so your left knee is at 90 degrees',
      'Stay upright and tuck your pelvis under',
      'Hold for 40 seconds feeling the deep stretch at the front of your right hip then switch',
    ],
  },
  {
    id: 'h7',
    name: 'Standing Hip Circle',
    muscle: 'hips',
    duration: 30,
    positions: ['standing'],
    feelings: ['tight', 'low-energy'],
    tip: 'Stand with feet shoulder-width apart and draw big slow circles with your hips. Go 5 times one way then switch — imagine you\'re hula hooping in slow motion.',
    steps: [
      'Stand with feet shoulder-width apart and hands on your hips',
      'Begin making large slow circles with your hips',
      'Make the circle as big as possible in each direction',
      'Do 5 full circles clockwise',
      'Reverse and do 5 full circles counter-clockwise',
    ],
  },

  // ─── GLUTES ─────────────────────────────────────────
  {
    id: 'g1',
    name: 'Glute Bridge Hold',
    muscle: 'glutes',
    duration: 40,
    positions: ['lying'],
    feelings: ['tight', 'sore'],
    tip: 'Press through your heels and squeeze your glutes hard at the top. Hold for 2 seconds before lowering. Most people rush this — the squeeze at the top is where all the benefit is.',
    steps: [
      'Lie on your back with knees bent and feet flat hip-width apart',
      'Press through your heels and lift your hips toward the ceiling',
      'Squeeze your glutes as hard as possible at the top',
      'Hold the squeeze for 2 full seconds',
      'Lower slowly and repeat for the full duration',
    ],
  },
  {
    id: 'g2',
    name: 'Seated Glute Stretch',
    muscle: 'glutes',
    duration: 40,
    positions: ['couch'],
    feelings: ['tight', 'sore'],
    tip: 'Cross one ankle over the opposite knee and sit tall. Gently lean forward from your hips to feel the stretch deep in your glute.',
    steps: [
      'Sit tall on the couch with feet flat on the floor',
      'Cross your right ankle over your left knee',
      'Keep your back straight and tall',
      'Lean gently forward from your hips until you feel it behind your right hip',
      'Hold for 30 seconds then switch sides',
    ],
  },
  {
    id: 'g3',
    name: 'Pigeon Pose',
    muscle: 'glutes',
    duration: 50,
    positions: ['lying'],
    feelings: ['tight', 'sore', 'stressed'],
    tip: 'Bring one shin parallel to the front of your mat and extend the other leg behind you. Square your hips and breathe deeply. This is widely considered the most effective glute and hip stretch in existence.',
    steps: [
      'Start on all fours and bring your right knee forward toward your right wrist',
      'Slide your right foot toward your left wrist so your shin is angled across',
      'Extend your left leg straight behind you on the floor',
      'Square your hips toward the floor as much as possible',
      'Hold for 40 to 50 seconds then switch sides',
    ],
  },
  {
    id: 'g4',
    name: 'Supine Figure Four',
    muscle: 'glutes',
    duration: 45,
    positions: ['lying'],
    feelings: ['tight', 'sore'],
    tip: 'Lie on your back, cross one ankle over the opposite knee and pull both legs toward your chest. This is a more accessible version of pigeon pose with identical benefits.',
    steps: [
      'Lie on your back with knees bent and feet flat',
      'Cross your right ankle over your left knee forming a figure four',
      'Flex your right foot to protect your knee',
      'Lift your left foot and pull both legs toward your chest',
      'Hold for 35 seconds feeling the stretch deep in your right glute then switch',
    ],
  },
  {
    id: 'g5',
    name: 'Standing Glute Squeeze',
    muscle: 'glutes',
    duration: 25,
    positions: ['standing'],
    feelings: ['low-energy', 'tight'],
    tip: 'Stand tall and squeeze both glutes as hard as you can for 5 seconds, then release. This activates dormant glutes — the root cause of most lower back pain.',
    steps: [
      'Stand tall with feet hip-width apart',
      'Squeeze both glutes as hard as you possibly can',
      'Hold the squeeze for 5 full seconds',
      'Release completely and feel the difference',
      'Repeat 5 times focusing on maximum contraction each time',
    ],
  },

  // ─── QUADS ──────────────────────────────────────────
  {
    id: 'q1',
    name: 'Standing Quad Hold',
    muscle: 'quads',
    duration: 30,
    positions: ['standing'],
    feelings: ['tight', 'sore'],
    tip: 'Keep your knees together and stand tall. Use a wall for balance if needed — it actually helps you stretch deeper.',
    steps: [
      'Stand near a wall and place one hand on it for balance',
      'Bend your right knee and bring your right foot toward your glute',
      'Hold your right ankle with your right hand',
      'Keep both knees together and stand tall',
      'Hold for 20 seconds then switch legs',
    ],
  },
  {
    id: 'q2',
    name: 'Lying Quad Stretch',
    muscle: 'quads',
    duration: 35,
    positions: ['lying'],
    feelings: ['tight', 'sore'],
    tip: 'Lie on your side and pull your top foot toward your glutes. Keep your knees together and your hips stacked — don\'t let your lower back arch.',
    steps: [
      'Lie on your right side with legs stacked on top of each other',
      'Bend your left knee and bring your left foot toward your left glute',
      'Hold your left ankle with your left hand',
      'Keep your knees together and your hips stacked',
      'Hold for 25 seconds then roll to the other side and switch',
    ],
  },
  {
    id: 'q3',
    name: 'Rectus Femoris Stretch',
    muscle: 'quads',
    duration: 40,
    positions: ['lying'],
    feelings: ['tight', 'sore'],
    tip: 'Lie face down and bend one knee, pulling your foot toward your glute. Squeeze the glute on that same side — this fully lengthens the rectus femoris, which crosses both the hip and knee.',
    steps: [
      'Lie face down flat on the floor with legs extended',
      'Bend your right knee and bring your right foot toward your right glute',
      'Reach back with your right hand and hold your ankle',
      'Squeeze your right glute firmly — this is the key step',
      'Hold for 30 seconds then switch sides',
    ],
  },
  {
    id: 'q4',
    name: 'Wall Quad Stretch',
    muscle: 'quads',
    duration: 40,
    positions: ['standing'],
    feelings: ['tight', 'sore'],
    tip: 'Stand facing a wall, rest one foot against it behind you with knee bent. This gives you a deeper quad stretch than the standard version by fully loading the stretch position.',
    steps: [
      'Stand facing a wall about one step away',
      'Bend your right knee and place the top of your right foot against the wall behind you',
      'Keep your right knee pointing straight down toward the floor',
      'Stand tall and tuck your pelvis slightly under',
      'Hold for 30 seconds feeling the deep stretch in your right quad then switch',
    ],
  },

  // ─── HAMSTRINGS ─────────────────────────────────────
  {
    id: 'ham1',
    name: 'Hamstring Reach',
    muscle: 'hamstrings',
    duration: 40,
    positions: ['standing', 'lying'],
    feelings: ['tight', 'sore'],
    tip: 'Keep a soft bend in your knee — never lock it out. Hinge from your hips, not your waist, and let your spine stay long rather than rounding.',
    steps: [
      'Stand tall with feet hip-width apart',
      'Keep a soft bend in both knees throughout',
      'Hinge forward from your hips keeping your back flat',
      'Let your arms hang down toward the floor',
      'Hold at the point of mild tension for 30 seconds',
    ],
  },
  {
    id: 'ham2',
    name: 'Lying Hamstring Raise',
    muscle: 'hamstrings',
    duration: 40,
    positions: ['lying'],
    feelings: ['tight', 'sore'],
    tip: 'Lie on your back and raise one leg toward the ceiling. Loop a towel or belt around your foot if you can\'t reach. Keep the other leg completely flat on the floor.',
    steps: [
      'Lie flat on your back with both legs extended',
      'Raise your right leg toward the ceiling with a slight bend in the knee',
      'Hold behind your thigh or loop a towel around your foot',
      'Keep your left leg completely flat on the floor',
      'Hold for 30 seconds then switch legs',
    ],
  },
  {
    id: 'ham3',
    name: 'PNF Hamstring Stretch',
    muscle: 'hamstrings',
    duration: 45,
    positions: ['lying'],
    feelings: ['tight', 'sore'],
    tip: 'Raise your leg and press it against your hands for 5 seconds like you\'re trying to push it down, then relax and pull it closer. This contract-relax method increases flexibility faster than any static stretch.',
    steps: [
      'Lie on your back and raise your right leg toward the ceiling',
      'Hold behind your thigh with both hands',
      'Press your leg into your hands as if trying to push it away for 5 seconds',
      'Relax completely and pull your leg gently closer to your chest',
      'Repeat the contract-relax cycle 3 times then switch legs',
    ],
  },
  {
    id: 'ham4',
    name: 'Single Leg Forward Fold',
    muscle: 'hamstrings',
    duration: 40,
    positions: ['couch', 'standing'],
    feelings: ['tight', 'sore'],
    tip: 'Extend one leg straight and keep the other bent. Hinge forward over the straight leg. This isolates one hamstring at a time for a much more focused stretch.',
    steps: [
      'Sit at the edge of your seat or on the floor',
      'Extend your right leg straight with a slight bend in the knee',
      'Keep your left foot flat on the floor with knee bent',
      'Hinge forward from your hips over your right leg keeping your back flat',
      'Hold for 30 seconds then switch legs',
    ],
  },

  // ─── CALVES ─────────────────────────────────────────
  {
    id: 'cal1',
    name: 'Standing Calf Raise',
    muscle: 'calves',
    duration: 30,
    positions: ['standing'],
    feelings: ['low-energy', 'tight'],
    tip: 'Press through the ball of your foot and hold at the top for a full second. Lower slowly — the downward phase is where the stretch happens.',
    steps: [
      'Stand tall with feet hip-width apart near a wall for balance',
      'Rise up slowly onto the balls of both feet',
      'Hold at the top for a full second squeezing your calves',
      'Lower back down very slowly over 3 seconds',
      'Repeat for the full duration focusing on the slow lowering phase',
    ],
  },
  {
    id: 'cal2',
    name: 'Wall Calf Stretch',
    muscle: 'calves',
    duration: 35,
    positions: ['standing'],
    feelings: ['tight', 'sore'],
    tip: 'Press your heel flat to the floor and lean into a wall. Keep your back leg completely straight for the gastrocnemius, then bend it slightly to target the soleus underneath.',
    steps: [
      'Stand facing a wall and place both hands on it at shoulder height',
      'Step your right foot back about 2 feet',
      'Press your right heel firmly into the floor',
      'Keep your right leg straight and lean toward the wall',
      'Hold for 20 seconds then bend your right knee slightly to stretch the soleus',
    ],
  },
  {
    id: 'cal3',
    name: 'Downward Dog Calf Pedal',
    muscle: 'calves',
    duration: 30,
    positions: ['lying'],
    feelings: ['tight', 'low-energy'],
    tip: 'In a downward dog position, alternate pressing each heel toward the floor. This dynamic stretch warms up the entire posterior chain — calves, hamstrings and back — at once.',
    steps: [
      'Start on all fours then lift your hips up and back into a downward dog shape',
      'Your body should form an inverted V shape',
      'Press your right heel toward the floor and hold for 2 seconds',
      'Switch and press your left heel toward the floor',
      'Alternate slowly for the full duration focusing on each calf',
    ],
  },
  {
    id: 'cal4',
    name: 'Seated Towel Calf Stretch',
    muscle: 'calves',
    duration: 35,
    positions: ['couch'],
    feelings: ['tight', 'sore'],
    tip: 'Sit with one leg extended and loop a towel around your foot. Pull your toes toward you and hold. This is the best calf stretch for people who can\'t easily get to the floor.',
    steps: [
      'Sit on the couch and extend your right leg straight',
      'Loop a towel or belt around the ball of your right foot',
      'Hold both ends of the towel and pull your toes toward you',
      'Keep your knee straight and feel the stretch in your calf',
      'Hold for 25 seconds then switch legs',
    ],
  },

  // ─── ANKLES ─────────────────────────────────────────
  {
    id: 'ank1',
    name: 'Ankle Circles',
    muscle: 'ankles',
    duration: 20,
    positions: ['couch', 'lying'],
    feelings: ['low-energy', 'sore'],
    tip: 'Make the circles as big as possible and go slowly. Do 5 clockwise then 5 counter-clockwise on each foot for the full benefit.',
    steps: [
      'Sit or lie down and lift one foot off the floor',
      'Draw large slow circles with your foot using your ankle',
      'Make the circles as big as possible',
      'Do 5 circles clockwise then 5 counter-clockwise',
      'Switch feet and repeat',
    ],
  },
  {
    id: 'ank2',
    name: 'Ankle Alphabet',
    muscle: 'ankles',
    duration: 40,
    positions: ['couch', 'lying'],
    feelings: ['tight', 'sore'],
    tip: 'Spell the alphabet with your big toe — capital letters only. This covers every range of motion in your ankle and is used by physical therapists after ankle sprains.',
    steps: [
      'Sit or lie down and lift your right foot off the floor',
      'Use your big toe as a pen and begin writing letters in the air',
      'Write each capital letter of the alphabet clearly and deliberately',
      'Move only your ankle and foot — keep your leg still',
      'Switch feet and repeat the alphabet',
    ],
  },
  {
    id: 'ank3',
    name: 'Banded Ankle Dorsiflexion',
    muscle: 'ankles',
    duration: 35,
    positions: ['couch', 'lying'],
    feelings: ['tight', 'sore'],
    tip: 'Flex your foot up as far as possible, hold for 2 seconds, then point it away. Ankle dorsiflexion is the most commonly limited movement and affects your squat, walking gait, and knee health.',
    steps: [
      'Sit or lie down with one leg extended',
      'Flex your foot pulling your toes as far toward your shin as possible',
      'Hold at the top for 2 full seconds',
      'Point your foot away as far as possible and hold for 2 seconds',
      'Repeat slowly for the full duration then switch feet',
    ],
  },

  // ─── GENERAL ────────────────────────────────────────
  {
    id: 'gen1',
    name: 'Full Body Stretch',
    muscle: 'general',
    duration: 45,
    positions: ['lying'],
    feelings: ['low-energy', 'stressed'],
    tip: 'Reach your arms overhead and point your toes away from you at the same time. Take a deep breath in as you stretch, and release everything on the exhale.',
    steps: [
      'Lie flat on your back with legs extended',
      'Reach both arms overhead as far as possible',
      'Point your toes away from you at the same time',
      'Take a long deep breath in as you stretch everything long',
      'Release everything on the exhale and repeat 3 to 5 times',
    ],
  },
  {
    id: 'gen2',
    name: 'Standing Side Stretch',
    muscle: 'general',
    duration: 30,
    positions: ['standing'],
    feelings: ['tight', 'stressed'],
    tip: 'Raise one arm overhead and lean to the opposite side, reaching your arm over. Keep your feet planted and your hips square — this opens the entire lateral line of the body at once.',
    steps: [
      'Stand tall with feet hip-width apart',
      'Raise your right arm straight overhead',
      'Lean your entire body to the left reaching your right arm over',
      'Keep both feet planted and your hips square',
      'Hold for 20 seconds then switch sides',
    ],
  },
  {
    id: 'gen3',
    name: 'World\'s Greatest Stretch',
    muscle: 'general',
    duration: 50,
    positions: ['standing', 'lying'],
    feelings: ['tight', 'low-energy'],
    tip: 'Step into a lunge, place the same-side hand on the floor, then rotate your top arm toward the ceiling. This single movement hits your hip flexors, thoracic spine, glutes and shoulders simultaneously.',
    steps: [
      'Step your right foot forward into a deep lunge',
      'Place your right hand on the floor inside your right foot',
      'Rotate your left arm up toward the ceiling opening your chest',
      'Hold for 3 seconds at the top of the rotation',
      'Return and repeat on the left side',
    ],
  },
  {
    id: 'gen4',
    name: 'Supine Windshield Wiper',
    muscle: 'general',
    duration: 40,
    positions: ['lying'],
    feelings: ['tight', 'sore', 'stressed'],
    tip: 'Lie on your back with knees bent and feet wider than hip width. Let your knees fall slowly side to side like windshield wipers. This decompresses the lumbar spine and mobilises both hips at once.',
    steps: [
      'Lie on your back with knees bent and feet wider than hip-width apart',
      'Extend both arms out to the sides at shoulder height',
      'Slowly let both knees fall to the right side',
      'Hold for 5 seconds then bring them back to center',
      'Let both knees fall to the left side and continue alternating slowly',
    ],
  },
];