export const ALL_STRETCHES = [
  {
    id: '1',
    name: 'Neck Rolls',
    muscle: 'neck',
    duration: 30,
    positions: ['couch', 'standing'],
    tip: 'Move slowly and let gravity do the work. Never roll your neck backwards — keep it to the sides and front only.',
  },
  {
    id: '2',
    name: 'Shoulder Shrugs',
    muscle: 'shoulders',
    duration: 30,
    positions: ['couch', 'standing'],
    tip: 'Lift your shoulders up toward your ears, hold for 2 seconds, then drop them down completely. Feel the tension release on the drop.',
  },
  {
    id: '3',
    name: 'Seated Spinal Twist',
    muscle: 'back',
    duration: 45,
    positions: ['couch'],
    tip: 'Sit tall before you twist — imagine a string pulling the top of your head toward the ceiling. Breathe out as you rotate deeper.',
  },
  {
    id: '4',
    name: 'Standing Quad Hold',
    muscle: 'quads',
    duration: 30,
    positions: ['standing'],
    tip: 'Keep your knees together and stand tall. Use a wall for balance if needed — there\'s no shame in it, it actually helps you stretch deeper.',
  },
  {
    id: '5',
    name: 'Standing Calf Raise',
    muscle: 'calves',
    duration: 30,
    positions: ['standing'],
    tip: 'Press through the ball of your foot and hold at the top for a full second. Lower slowly — the downward phase is where the stretch happens.',
  },
  {
    id: '6',
    name: 'Supine Knee Hug',
    muscle: 'back',
    duration: 45,
    positions: ['lying'],
    tip: 'Pull both knees gently into your chest and let your lower back press flat into the floor. Rock side to side slightly for a bonus massage.',
  },
  {
    id: '7',
    name: 'Lying Hip Stretch',
    muscle: 'hips',
    duration: 45,
    positions: ['lying'],
    tip: 'Cross one ankle over the opposite knee and flex that foot to protect your knee joint. The closer you pull your legs to your chest, the deeper the stretch.',
  },
  {
    id: '8',
    name: 'Chest Opener',
    muscle: 'chest',
    duration: 30,
    positions: ['couch', 'standing'],
    tip: 'Clasp your hands behind your back and gently squeeze your shoulder blades together. Keep your chin level — don\'t let your head drop forward.',
  },
  {
    id: '9',
    name: 'Ankle Circles',
    muscle: 'ankles',
    duration: 20,
    positions: ['couch', 'lying'],
    tip: 'Make the circles as big as possible and go slowly. Do 5 clockwise then 5 counter-clockwise on each foot for the full benefit.',
  },
  {
    id: '10',
    name: 'Full Body Stretch',
    muscle: 'general',
    duration: 45,
    positions: ['lying'],
    tip: 'Reach your arms overhead and point your toes away from you at the same time. Take a deep breath in as you stretch, and release everything on the exhale.',
  },
  {
    id: '11',
    name: 'Hamstring Reach',
    muscle: 'hamstrings',
    duration: 40,
    positions: ['standing', 'lying'],
    tip: 'Keep a soft bend in your knee — never lock it out. Hinge from your hips, not your waist, and let your spine stay long rather than rounding.',
  },
  {
    id: '12',
    name: 'Hip Flexor Lunge',
    muscle: 'hips',
    duration: 40,
    positions: ['standing'],
    tip: 'Tuck your pelvis slightly under — this is the key move most people miss. You should feel the stretch at the front of your back leg\'s hip, not your knee.',
  },
];